#!/bin/bash
set -euxo pipefail
rm -rf venv .venv.tmp
python3 -m venv .venv.tmp
./.venv.tmp/bin/pip install -e '.[dev]' -c requirements.txt -c requirements-dev.txt
mv .venv.tmp .venv
python3 -m venv .venv  # handle relocation
