github:
  owner: getsentry
  repo: devservices
changelogPolicy: auto
targets:
  - name: github
  - name: pypi
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi

requireNames:
  - /^devservices-darwin$/
  - /^devservices-linux$/
