name: 'CI'
description: 'Validates sentry-shared-kafka devservices config'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  files-changed:
    name: detect what files changed
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    outputs:
      devservices-files-changed: ${{ steps.changes.outputs.devservices-files-changed   }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        name: Check for file changes
        id: changes
        with:
          token: ${{ github.token }}
          filters: |
            devservices-files-changed:
              - 'devservices/**'
              - '.github/workflows/ci.yml'
              - 'requirements-dev.txt'
  ci:
    runs-on: ubuntu-24.04
    needs: files-changed
    if: ${{ needs.files-changed.outputs.devservices-files-changed == 'true' }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        name: Checkout repository
      - uses: getsentry/action-validate-devservices-config@02a078d1280293e6598cabfbd318a01609c12c83
        name: Validate devservices config
        with:
          requirements-file-path: requirements-dev.txt

