name: Test

on:
  push:
    branches:
      - main
      - release/**
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: ["3.11", "3.12"]
    steps:
      - name: Configure git
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "test"
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev-frozen.txt
          pip install -e .
      - name: Run tests
        run: pytest --cov --junitxml=junit.xml -o junit_family=legacy
      - name: Upload results to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: getsentry/devservices
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@1b5b448b98e58ba90d1a1a1d9fcb72ca2263be46 # v1.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
